version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
    groups:
      npm-runtime:
        dependency-type: production
      npm-development:
        dependency-type: development
  - package-ecosystem: cargo
    directory: /src-tauri
    schedule:
      interval: weekly
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
